# Numpy

numerical Python
https://numpy.org/

In [2]:
import numpy as np

In [3]:
a1=np.array([])
a1


array([], dtype=float64)

In [46]:
a2=np.array([1,2,3,4])
a2

array([1, 2, 3, 4])

In [47]:
a2.max()


np.int64(4)

In [48]:
a2.min()

np.int64(1)

In [42]:
a2.mean()

np.float64(2.5)

In [11]:
a2.ndim

1

In [12]:
a2.shape

(4,)

### Different ways of creating numpys array

In [17]:
a1=np.array([1,2,3,4])

In [18]:
a1

array([1, 2, 3, 4])

In [20]:
a2=np.arange(1,25)
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [25]:
for i in range (1,25):
    print(i,end=" ")


1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 

In [36]:
for i in range (1,25,4):# start,stop,jump
    print(i,end=" ")


1 5 9 13 17 21 

In [27]:
a3=np.ones(5)
a3

array([1., 1., 1., 1., 1.])

In [35]:
a3=np.ones([5,3])
a3#(5 rows,3 coloums )

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
a4=np.zeros((2,1))
a4

array([[0.],
       [0.]])

In [32]:
a4=np.zeros((3,4))
a4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
a4.shape

(3, 4)

In [49]:
a3=np.ones(5,dtype="complex")
a3

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])

In [51]:
a3=np.ones(5,dtype="bool")
a3

array([ True,  True,  True,  True,  True])

In [54]:
a5=np.identity(4)#diagonaly element
a5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
a6=np.random.rand(3,2)
a6

array([[0.64837126, 0.37427214],
       [0.99727533, 0.20756856],
       [0.88931273, 0.44095304]])

In [58]:
a6=np.random.rand(5)
a6

array([0.28970481, 0.72011525, 0.82195129, 0.85590606, 0.40459708])

In [60]:
a7=np.random.random([5,4])
a7

array([[0.98994996, 0.61846584, 0.7137734 , 0.52066247],
       [0.47006408, 0.53407184, 0.10407836, 0.45529909],
       [0.41766148, 0.94920936, 0.22717681, 0.44092076],
       [0.18024831, 0.65356008, 0.02489845, 0.86296151],
       [0.61031771, 0.09762213, 0.58612706, 0.60232896]])

In [67]:
a8=np.random.randint(12,45,5)
a8# low,high,size

array([24, 39, 34, 28, 41], dtype=int32)

In [69]:
a9=np.array([[1,2,3,4],[11,22,33,44],[12,13,14,15]])
a9

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [12, 13, 14, 15]])

In [71]:
a9=np.array([1,2,3,4])
a9.ndim

1

In [79]:
a9=np.array([[[1,2,3,4]]])
a9.ndim#bracket count

3

In [81]:
a10=np.ravel(a9)
a10.ndim# it is use anywhere

1

In [82]:
a9=a9.flatten()
a9.ndim# restirct to numpy

1

# slicing and reshaping

In [84]:
a11=np.arange(1,23,3)
a11

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [85]:
a11[4:5]

array([13])

In [87]:
a11[3:-2]

array([10, 13, 16])

In [88]:
a11[::-1]

array([22, 19, 16, 13, 10,  7,  4,  1])

In [89]:
a11[::1]

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [90]:
a11[::-2]

array([22, 16, 10,  4])

In [91]:
a11[::2]

array([ 1,  7, 13, 19])

In [92]:
a11[::3]

array([ 1, 10, 19])

In [94]:
a11[-3:1:-1]

array([16, 13, 10,  7])

In [95]:
a11[-2:1:-1]

array([19, 16, 13, 10,  7])

In [96]:
a11[-3:0:-1]

array([16, 13, 10,  7,  4])

In [100]:
a=np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [101]:
a[1]

array([5, 6, 7, 8, 9])

In [104]:
a[:,1]

array([ 1,  6, 11, 16, 21])

In [105]:
a[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [107]:
a[2:,:-1]

array([[10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [10]:
a2=np.arange(25).reshape(5,5)
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
a2[1::]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
a2[1:3:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
a2[::-1]#-1 opposite

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [29]:
a2[:,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22]])

# array operation

In [30]:
a1=[1,2,3,4]
a2=[5,6,7,8]

In [31]:
a1+a2

[1, 2, 3, 4, 5, 6, 7, 8]

In [51]:
a2*2#no is repeat 

array([  2,  44, 222, 444])

In [38]:
a1/a2

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [40]:
a1*a2

TypeError: can't multiply sequence by non-int of type 'list'

In [41]:
a1**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [42]:
a1=np.array([1,2,3,4])
a2=np.array([1,22,111,222])

In [43]:
a1+a2

array([  2,  24, 114, 226])

In [44]:
a1-a2

array([   0,  -20, -108, -218])

In [45]:
a2/a1

array([ 1. , 11. , 37. , 55.5])

In [46]:
a1//2

array([0, 1, 1, 2])

In [47]:
a1*a2

array([  1,  44, 333, 888])

In [48]:
a1**3

array([ 1,  8, 27, 64])

In [50]:
a1*3#no is multiply by 3

array([ 3,  6,  9, 12])

# array manipulation

In [61]:
a1=np.array([1,2,3,4])
a2=np.array([22,2,2,2])

In [62]:
np.hstack([a1,a2])

array([ 1,  2,  3,  4, 22,  2,  2,  2])

In [63]:
np.vstack([a1,a2])

array([[ 1,  2,  3,  4],
       [22,  2,  2,  2]])

In [64]:
a22=a2*2
a22

array([44,  4,  4,  4])

In [57]:
a2=np.arange(8)
a2#array splitting works only for the factor

array([0, 1, 2, 3, 4, 5, 6, 7])

In [58]:
np.split(a2,2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [65]:
a11=a2/2
a11

array([11.,  1.,  1.,  1.])

In [81]:
a2=np.arange(30)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [83]:
np.split(a2,5)

[array([0, 1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17]),
 array([18, 19, 20, 21, 22, 23]),
 array([24, 25, 26, 27, 28, 29])]

In [84]:
np.linspace(11,45,9)

array([11.  , 15.25, 19.5 , 23.75, 28.  , 32.25, 36.5 , 40.75, 45.  ])

In [89]:
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [91]:
a1=np.arange(40)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [94]:
np.split(a1,5)

[array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20, 21, 22, 23]),
 array([24, 25, 26, 27, 28, 29, 30, 31]),
 array([32, 33, 34, 35, 36, 37, 38, 39])]

In [98]:
a1=np.array([1,2,3])
a2=np.array([1,1,1])
a3=np.array([2,2,2])

In [100]:
np.hstack([a1,a2,a3])

array([1, 2, 3, 1, 1, 1, 2, 2, 2])

In [101]:
np.vstack([a1,a2,a3])

array([[1, 2, 3],
       [1, 1, 1],
       [2, 2, 2]])